name: Deploy GitHub Pages

on:
  push:
    branches: [main]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: pages
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4 # v4 es la versión estable actual más común

      - uses: actions/setup-node@v4
        with:
          node-version: "24" # Aquí ya estás forzando Node 24 para tu código
          cache: yarn

      - name: Enable Corepack (Yarn)
        run: corepack enable

      - name: Install
        run: yarn install --frozen-lockfile

      - name: Build
        env:
          VITE_BASE_PATH: /${{ github.event.repository.name }}/
        run: yarn build

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3 # Reajustado a v3 (que es la más estable para Pages)
        with:
          path: dist

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4 # v4 es la recomendada actualmente
